apiVersion: v1
kind: Service
metadata:
  name: python
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    faas_function: python
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 1
  rollbackTo:
    revision: 0
  selector:
    matchLabels:
      faas_function: python
  template:
    metadata:
      name: python
      labels:
        faas_function: python
    spec:
      containers:
      - env:
        - name: fprocess
          value: python3 time2py.py
        - name: https_proxy
          value: $https_proxy
        - name: no_proxy
          value: gateway
        - name: read_timeout
          value: "60"
        - name: write_timeout
          value: "60"
        image: jockdarock/time2py:latest
        imagePullPolicy: Always
        name: python
      nodeName: aci-connector